### ISSUE TITLE
Nice RAT

### ISSUE THREAD

**Issue by FLUORESCENTXX** [PurgerDev/PurgeStealer#15]
Imagine skidding mercurial and then hiding the code and putting a rat on the app lol

**Comment by russianheavy1337** [comment]
It's really obvious you have brain damage its not even made in the same language as mercurial lol.

**Comment by FLUORESCENTXX** [comment]
mm the owner also keeps spamming it lol.

**Comment by FLUORESCENTXX** [comment]
u know if he made it open source he prob copy + pasted some other builder

**Comment by daddyevox** [comment]
Are you stupid LOL. First off its basically open sourced and we have over a 100 kids that can vouch it works properly. 

Its literally open sourced and it is very obvious you have brain damage.

**Comment by FLUORESCENTXX** [comment]
its not open source
