### ISSUE TITLE
Missing DLLS

### ISSUE THREAD

**Issue by vinnyaintblackbro** [PurgerDev/PurgeStealer#4]
Missing DLLS
![image](https://user-images.githubusercontent.com/97368727/150647293-f91520f1-f06b-49d2-b44a-6f6067a054cf.png)
![image](https://user-images.githubusercontent.com/97368727/150647297-6ac4ae83-c6a8-479e-85e3-0899c62fc3f6.png)

**Comment by Supabit** [comment]
You need to install Visual C++, however I think that this repository is a scam.

**Comment by PurgerDev** [comment]
Did you extract all of the files out of the archive?
